# Default initial positions for display_so_arm100_rviz's ros2_control fake system

initial_positions:
  Elbow: 0
  Humeral_Rotation: 0
  Shoulder_Pitch: 0
  Shoulder_Yaw: 0
  Wrist_Pitch: 0
  Wrist_Roll: 0
  Wrist_Yaw: 0