# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    so-arm100-groups_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

so-arm100-groups_controller:
  ros__parameters:
    joints:
      - Shoulder_Pitch
      - Shoulder_Yaw
      - Humeral_Rotation
      - Elbow
      - Wrist_Roll
      - Wrist_Yaw
      - Wrist_Pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity